In [1]:
from darli.models import RobotModelCasadi
from robot_descriptions import z1_description

model = RobotModelCasadi(z1_description.URDF_PATH)

In [2]:
model.com

CoM(position=Function(com_position:(q[6])->(com_position[3]) SXFunction), velocity=Function(com_velocity:(q[6],v[6])->(com_velocity[3]) SXFunction), acceleration=Function(com_acceleration:(q[6],v[6],dv[6])->(com_acceleration[3]) SXFunction), jacobian=Function(com_jacobian:(q[6])->(com_jacobian[3x6]) SXFunction), jacobian_dt=Function(com_jacobian_dt:(q[6],v[6])->(com_jacobian_dt[3x6]) SXFunction))

In [3]:
model.gravity

Function(gravity:(q[6])->(gravity[6]) SXFunction)

In [4]:
model.joint_names

['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

In [5]:
model.coriolis

Function(coriolis:(q[6],v[6])->(coriolis[6]) SXFunction)

In [6]:
model.add_bodies({'ee': 'link06'})

In [7]:
model.body('ee')

In [8]:
model.body('ee').jacobian.local

Function(ee_jacobian_local:(q[6])->(jacobian[6x6]) SXFunction)

In [9]:
from darli.models import RobotModelPinocchio
from robot_descriptions import z1_description

model2 = RobotModelPinocchio(z1_description.URDF_PATH)

In [10]:
import numpy as np

q = np.array([0, 0, 0, 0, 0, 0])
v = np.array([0, 0, 0, 0, 0, 0])

In [11]:
model2.update(q, v)

In [12]:
model2.com.position

array([-9.99593217e-02,  3.77542243e-05,  1.25879489e-01])

In [13]:
model.gravity(q)

DM([0, 3.86971, -4.56449, -1.03434, 0, -0.000491618])

In [14]:
model2.gravity

array([ 0.00000000e+00,  3.86970834e+00, -4.56448506e+00, -1.03433950e+00,
        0.00000000e+00, -4.91617978e-04])

In [15]:
model2.add_bodies({'ee': 'link06'})

In [16]:
model2.body('ee').position

array([-0.0128,  0.    ,  0.1605])

In [17]:
model2.add_bodies(['link05'])

In [18]:
model2.body('ee').position

array([-0.0128,  0.    ,  0.1605])

In [19]:
model2.body('link05').position

array([-0.062 ,  0.    ,  0.1605])

In [20]:
model2.update(np.random.rand(6), np.random.rand(6))