In [1]:
from darli.backend import CasadiBackend, PinocchioBackend
from darli.modeling import Robot, Parametric, Functional
from darli.modeling.parametric import Functional as PFunctional
import numpy as np

np.random.seed(0)
import casadi as cs
from robot_descriptions import z1_description

# Initializing the RobotModel class
# model = Parametric(CasadiBackend(z1_description.URDF_PATH))
model = PFunctional(CasadiBackend(z1_description.URDF_PATH))
functional = Functional(CasadiBackend(z1_description.URDF_PATH))

In [2]:
q, v = np.random.rand(2, model.nq)

q, v

(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411]),
 array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
        0.52889492]))

In [3]:
# model._parameters = model.backend.base_parameters()

## Energy

In [4]:
# model.update(q, v, np.zeros(model.nv))

model.energy.kinetic(q, v, model.backend.base_parameters()), model.energy.potential(q, model.backend.base_parameters())

(DM(0.133365), DM(5.2694))

In [5]:
functional.energy.kinetic(q, v), functional.energy.potential(q)

(DM(0.133365), DM(5.2694))

## gravity

In [6]:
model.gravity(q, model.backend.base_parameters())

DM([7.45181e-18, 4.80066, -1.55477, 0.278, 0.13055, 0.000804553])

In [7]:
functional.gravity(q)

DM([0, 4.80066, -1.55477, 0.278, 0.13055, 0.000804553])

# Coriolis

In [8]:
model.coriolis(q, v, model.backend.base_parameters())

DM([-0.0407087, -0.228641, 0.109978, -0.0233072, -0.00279174, -0.000362477])

In [9]:
functional.coriolis(q, v)

DM([-0.0407087, -0.228641, 0.109978, -0.0233072, -0.00279174, -0.000362477])

## Inertia

In [10]:
model.inertia(q, model.backend.base_parameters())

DM(
[[0.101317, 0.00132155, 0.00455971, 0.00176692, -0.0060523, -0.000231951], 
 [0.00132155, 0.143785, -0.0112658, 0.0129927, 0.00219007, 6.80896e-05], 
 [0.00455971, -0.0112658, 0.127425, 0.0280916, -0.00224463, -9.58142e-06], 
 [0.00176692, 0.0129927, 0.0280916, 0.0118326, 2.93431e-06, 4.7437e-05], 
 [-0.0060523, 0.00219007, -0.00224463, 2.93431e-06, 0.00261917, 2.77156e-05], 
 [-0.000231951, 6.80896e-05, -9.58142e-06, 4.7437e-05, 2.77156e-05, 0.000183886]])

In [11]:
np.array(functional.inertia(q))

array([[ 1.01317059e-01,  1.32154549e-03,  4.55970917e-03,
         1.76692070e-03, -6.05229994e-03, -2.31951305e-04],
       [ 1.32154549e-03,  1.43784536e-01, -1.12658284e-02,
         1.29926548e-02,  2.19007357e-03,  6.80895936e-05],
       [ 4.55970917e-03, -1.12658284e-02,  1.27425086e-01,
         2.80916044e-02, -2.24462745e-03, -9.58141885e-06],
       [ 1.76692070e-03,  1.29926548e-02,  2.80916044e-02,
         1.18325809e-02,  2.93431393e-06,  4.74370283e-05],
       [-6.05229994e-03,  2.19007357e-03, -2.24462745e-03,
         2.93431393e-06,  2.61917371e-03,  2.77155917e-05],
       [-2.31951305e-04,  6.80895936e-05, -9.58141885e-06,
         4.74370283e-05,  2.77155917e-05,  1.83886435e-04]])

## Forward dynamics

In [12]:
model.forward_dynamics(q, v, np.zeros(model.nv), model.backend.base_parameters())

DM([-0.927408, -30.2987, 17.7486, -34.2518, -12.6317, 15.3673])

In [13]:
functional.forward_dynamics(q, v, np.zeros(model.nv))

DM([-0.927408, -30.2987, 17.7486, -34.2518, -12.6317, 15.3673])

## Inverse dynamics

In [14]:
model.inverse_dynamics(q, v, np.zeros(model.nv), model.backend.base_parameters())

DM([0.0407087, 5.0293, -1.66475, 0.301307, 0.133342, 0.00116703])

In [15]:
functional.inverse_dynamics(q, v, np.zeros(model.nv))

DM([0.0407087, 5.0293, -1.66475, 0.301307, 0.133342, 0.00116703])