In [5]:
from darli.backend import CasadiBackend, PinocchioBackend
from darli.modeling import Robot, Parametric, Functional
from darli.modeling.parametric import Functional as PFunctional
import numpy as np

np.random.seed(0)
import casadi as cs
from robot_descriptions import z1_description

# Initializing the RobotModel class
# model = Parametric(CasadiBackend(z1_description.URDF_PATH))
model = PFunctional(CasadiBackend(z1_description.URDF_PATH))
functional = Functional(CasadiBackend(z1_description.URDF_PATH))

In [6]:
q, v = np.random.rand(2, model.nq)

q, v

(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411]),
 array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
        0.52889492]))

In [7]:
model._parameters = model.backend.base_parameters()

In [10]:
# model.update(q, v, np.zeros(model.nv))

model.energy.kinetic(q, v, model.backend.base_parameters()), model.energy.potential(q, model.backend.base_parameters())

(DM(0.133365), DM(5.2694))

In [11]:
functional.energy.kinetic(q, v), functional.energy.potential(q)

(DM(0.133365), DM(5.2694))

In [19]:
with np.printoptions(precision=5, suppress=True):
    print(model.inertia(q, model.backend.base_parameters()))


[[0.101317, 0.00132155, 0.00455971, 0.00176692, -0.0060523, -0.000231951], 
 [4.80198, 4.94444, 4.78939, 4.81365, 4.80285, 4.80073], 
 [-1.55021, -1.56603, -1.42734, -1.52668, -1.55701, -1.55478], 
 [0.279767, 0.290993, 0.306092, 0.289833, 0.278003, 0.278048], 
 [0.124498, 0.13274, 0.128305, 0.130553, 0.133169, 0.130578], 
 [0.000572602, 0.000872643, 0.000794972, 0.00085199, 0.000832269, 0.000988439]]


In [20]:
with np.printoptions(precision=5, suppress=True):
    print(np.array(functional.inertia(q)))

[[ 0.10132  0.00132  0.00456  0.00177 -0.00605 -0.00023]
 [ 0.00132  0.14378 -0.01127  0.01299  0.00219  0.00007]
 [ 0.00456 -0.01127  0.12743  0.02809 -0.00224 -0.00001]
 [ 0.00177  0.01299  0.02809  0.01183  0.       0.00005]
 [-0.00605  0.00219 -0.00224  0.       0.00262  0.00003]
 [-0.00023  0.00007 -0.00001  0.00005  0.00003  0.00018]]
